// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package remoterules;

public final class RulesTesterImplementation_Stub
    extends java.rmi.server.RemoteStub
    implements remoterules.RulesTesterInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_runRules_0;
    
    static {
	try {
	    $method_runRules_0 = remoterules.RulesTesterInterface.class.getMethod("runRules", new java.lang.Class[] {java.lang.String[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RulesTesterImplementation_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of runRules(String[])
    public java.lang.String runRules(java.lang.String[] $param_arrayOf_String_1)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_runRules_0, new java.lang.Object[] {$param_arrayOf_String_1}, 303397731284885322L);
	return ((java.lang.String) $result);
    }
}
